---
title: "exercise_2"
format: html
editor: visual
---

# Ejercicio 2.

### Write a text document (txt, doc, R markdown or Quarto) designing the steps you think would be necessary to process the same data as before, but for all municipalities in Spain, returning daily summaries of meteorological data for each municipality in 2020. Don’t write code, just write the strategy you’d follow and the steps you’d take to achieve this.

Para procesar la información meteorológica de todos los municipios de España, utilizaría una combinación de los paquetes arrow y duckdb para seleccionar y filtrar las variables que buscamos analizar. Los pasos a seguir serían los siguientes:

1 - Abrir el archivo parquet mediante la libreria "arrow" con la función "open_dataset()". Esto permitiría leer los metadatos del archivo y visualizar el contenido de las columnas.

2 - Cargar el archivo descargado mediante duck_db a través de las funciones "dbConnect()" y "dbGetQuery" y seleccionar columnas relacionadas con la fecha, municipio, las variables principales (humedad relativa, temperatura y precipitación) y geometría.
